version: "3"
networks:
  community:
    driver: bridge
services:
  community-client:
    build:
      context: ./community-client
      dockerfile: Dockerfile
      args:
        REACT_APP_KAKAO_REDIRECT_URI: ${REACT_APP_KAKAO_REDIRECT_URI}
        REACT_APP_KAKAO_RESTFUL_API_KEY: ${REACT_APP_KAKAO_RESTFUL_API_KEY}
        REACT_APP_BASE_PROFILE_IMG: ${REACT_APP_BASE_PROFILE_IMG}
        NGINX_CONF: ${NGINX_CONFIG_FILE}
    container_name: community-client
    networks:
      - community
    ports:
      - 80:80
    volumes:
      - /app/node_modules
      - ./community-client:/app
    stdin_open: true
    depends_on:
      - community-server

  community-server:
    build:
      dockerfile: Dockerfile
      context: ./community-server
    container_name: community-server
    networks:
      - community
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=docker_compose
      - WAIT_HOSTS=community-mysql:3306
    volumes:
      - /app/node_modules
      - ./community-server:/app
    depends_on:
      - community-mysql
    env_file:
      - ./community-server/.env

  community-mysql:
    image: mysql:5.7
    container_name: community-mysql
    networks:
      - community
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DBNAME}
